<?php

/**
* Field: Button Group
* @version 2.0.0
* @since 2.0.0
*/

namespace sacf\field;

class buttongroup extends base {
	
	protected $defaults = array(
		'choices' => array(),
		'allow_null' => 0,
		'default_value' => '',
		'layout' => 'horizontal',
		'return_format' => 'value',
	);
	
	/**
	* Constructor method
	* 
	* @param String $label Label for this field
	* @param String $name Alternative name for this field (optional - autogenerated from Label if left out)
	*/
	public function __construct($label, $name = false) {
		parent::__construct($label, $name, 'button_group');
	}
	
	/**
	* Set availible choices
	*
	* @param array $array <code>array('key' => 'value', 'red' => 'Red')</code>
	* @return void
	*/
	public function choices($array) {
		$this->options['choices'] = $array;
		return $this;
	}
	
	/**
	* Allow Null?
	*
	* @param boolean $bool is null allowed?
	* @return void
	*/
	public function allow_null($bool = true) {
		$this->options['allow_null'] = $bool;
		return $this;
	}

	/**
	 * Appears when creating a new post
	 *
	 * @param String $string key of the default value
	 * @return void
	 */
	public function default_value($string) {
		$this->options['value'] = $string;
		return $this;
	}
	
	/**
	 * Layout
	 *
	 * @param string $string <code>vertical</code> or <code>horizontal</code>
	 * @return void
	 */
	public function layout($string = 'vertical') {
		$this->options['layout'] = $string;
		return $this;
	}
	
	/**
	 * Specify the returned value on front end
	 *
	 * @param string $string <code>value</code>, <code>label</code> or <code>array</code>, 
	 * @return void
	 */
	public function return_format($string) {
		$this->options['return_format'] = $string;
		return $this;
	}
	
}
